# Generated by Selenium IDE
import pytest

from selenium import webdriver
from selenium.webdriver.common.by import By

from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service


@pytest.fixture()
def director(texty=''):
    return texty


class TestAgregardirector():  
      
    def setup_method(self):
        chrome_options = Options()
        chrome_options.add_argument("--ignore-certificate-errors")
        chrome_options.add_experimental_option('excludeSwitches', ['enable-logging'])
        self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)

    def teardown_method(self):
        self.driver.quit()

    
    def test_agregardirector(self, director):
        if director != '':
            self.driver.get("http://localhost:8001/")
            self.driver.set_window_size(1382, 744)
            self.driver.find_element(By.ID, ":r1:-tab-1").click()    
            self.driver.find_element(By.ID, "add-director-btn").click()
            self.driver.find_element(By.ID, "name").click()
            self.driver.find_element(By.ID, "name").send_keys(director)
            self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()

    
test= TestAgregardirector()
test.setup_method()
#----AGREGAR DIRECTORES-----#
test.test_agregardirector('Quentin Tarantino')
test.test_agregardirector('Stanley Kubrick')
test.teardown_method()


