# Generated by Selenium IDE
import pytest

from selenium import webdriver
from selenium.webdriver.common.by import By

from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

@pytest.fixture()
def pelicula(titulo='', des='', amo='', director_id=''):
    return DataPelicula(titulo, des, amo, director_id)

class DataPelicula():
    def __init__(self, titulo='', des='', amo='', director_id=str()):        
        self.titulo = titulo
        self.des = des
        self.amo = amo
        self.director_id = director_id

class TestAgregarpelicula():  

    
    def setup_method(self):
        chrome_options = Options()
        chrome_options.add_argument("--ignore-certificate-errors")
        chrome_options.add_experimental_option('excludeSwitches', ['enable-logging'])
        self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
       

    def teardown_method(self):
        self.driver.quit()

    
    def test_agregarpelicula(self, pelicula):
        if pelicula.titulo != '':
            self.driver.get("http://localhost:8001/")
            self.driver.set_window_size(1382, 744)
            self.driver.find_element(By.ID, "add-movie-btn").click()
            self.driver.find_element(By.ID, "title").click()
            self.driver.find_element(By.ID, "title").send_keys(pelicula.titulo)
            self.driver.find_element(By.ID, "description").click()
            self.driver.find_element(By.ID, "description").send_keys(pelicula.des)
            self.driver.find_element(By.ID, "year").click()
            self.driver.find_element(By.ID, "year").send_keys(pelicula.amo)
            self.driver.find_element(By.ID, "director_id").click()
            cad= "//select[@id='director_id']/option[@value='"+pelicula.director_id+"']"
            self.driver.find_element(By.XPATH, cad).click()
            self.driver.find_element(By.CSS_SELECTOR, ".h-min > .flex").click()




test1= TestAgregarpelicula()
test1.setup_method()

#----AGREGAR PELICULAS-----#
#----AGREGAR PELICULAS CRISTOPHER NOLAN-----#
test1.test_agregarpelicula(DataPelicula('Pelicula1', 'Pelicula1', '2010', '1'))
test1.test_agregarpelicula(DataPelicula('Pelicula1', 'Pelicula5', '2014', '1'))
test1.test_agregarpelicula(DataPelicula('Pelicula1', 'Pelicula6', '2015', '1'))

#----AGREGAR PELICULAS DEMAS DIRECTORES----#
test1.test_agregarpelicula(DataPelicula('Pelicula2', 'Pelicula2', '2011', '2'))
test1.test_agregarpelicula(DataPelicula('Pelicula3', 'Pelicula3', '2012', '3'))
test1.test_agregarpelicula(DataPelicula('Pelicula4', 'Pelicula4', '2013', '4'))

test1.teardown_method()



